# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: image_service.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13image_service.proto\x12\x0cimageservice\"#\n\x12ImageUploadRequest\x12\r\n\x05image\x18\x01 \x01(\x0c\"&\n\x13ImageUploadResponse\x12\x0f\n\x07message\x18\x01 \x01(\t2b\n\x0cImageService\x12R\n\x0bUploadImage\x12 .imageservice.ImageUploadRequest\x1a!.imageservice.ImageUploadResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'image_service_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_IMAGEUPLOADREQUEST']._serialized_start=37
  _globals['_IMAGEUPLOADREQUEST']._serialized_end=72
  _globals['_IMAGEUPLOADRESPONSE']._serialized_start=74
  _globals['_IMAGEUPLOADRESPONSE']._serialized_end=112
  _globals['_IMAGESERVICE']._serialized_start=114
  _globals['_IMAGESERVICE']._serialized_end=212
# @@protoc_insertion_point(module_scope)
