# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto3/model_service_proto.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n proto3/model_service_proto.proto\x12\x08trt_yolo\"#\n\x12ImageUploadRequest\x12\r\n\x05image\x18\x01 \x01(\x0c\"N\n\x11\x44\x65tectionResponse\x12\x1c\n\x05\x62oxes\x18\x01 \x03(\x0b\x32\r.trt_yolo.Box\x12\r\n\x05\x63onfs\x18\x02 \x03(\x02\x12\x0c\n\x04\x63lss\x18\x03 \x03(\x05\"A\n\x03\x42ox\x12\r\n\x05x_min\x18\x01 \x01(\x02\x12\r\n\x05y_min\x18\x02 \x01(\x02\x12\r\n\x05x_max\x18\x03 \x01(\x02\x12\r\n\x05y_max\x18\x04 \x01(\x02\x32Z\n\x0eTrtYoloService\x12H\n\x0bUploadImage\x12\x1c.trt_yolo.ImageUploadRequest\x1a\x1b.trt_yolo.DetectionResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'proto3.model_service_proto_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_IMAGEUPLOADREQUEST']._serialized_start=46
  _globals['_IMAGEUPLOADREQUEST']._serialized_end=81
  _globals['_DETECTIONRESPONSE']._serialized_start=83
  _globals['_DETECTIONRESPONSE']._serialized_end=161
  _globals['_BOX']._serialized_start=163
  _globals['_BOX']._serialized_end=228
  _globals['_TRTYOLOSERVICE']._serialized_start=230
  _globals['_TRTYOLOSERVICE']._serialized_end=320
# @@protoc_insertion_point(module_scope)
