# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from . import model_service_proto_pb2 as proto3_dot_model__service__proto__pb2


class TrtYoloServiceStub(object):
    """Definición del servicio
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.UploadImage = channel.unary_unary(
                '/trt_yolo.TrtYoloService/UploadImage',
                request_serializer=proto3_dot_model__service__proto__pb2.ImageUploadRequest.SerializeToString,
                response_deserializer=proto3_dot_model__service__proto__pb2.DetectionResponse.FromString,
                )


class TrtYoloServiceServicer(object):
    """Definición del servicio
    """

    def UploadImage(self, request, context):
        """Define un método para subir imágenes
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_TrtYoloServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'UploadImage': grpc.unary_unary_rpc_method_handler(
                    servicer.UploadImage,
                    request_deserializer=proto3_dot_model__service__proto__pb2.ImageUploadRequest.FromString,
                    response_serializer=proto3_dot_model__service__proto__pb2.DetectionResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'trt_yolo.TrtYoloService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class TrtYoloService(object):
    """Definición del servicio
    """

    @staticmethod
    def UploadImage(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/trt_yolo.TrtYoloService/UploadImage',
            proto3_dot_model__service__proto__pb2.ImageUploadRequest.SerializeToString,
            proto3_dot_model__service__proto__pb2.DetectionResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
